### ISSUE TITLE
Maven fails to compile

### ISSUE THREAD

**Issue by CarlosAugustoP** [CarlosAugustoP/hunt-hub#5]
despite the IDE recognizing domain as a valid dependency in pom xml and also in taskstepdefinitionsjava, maven will fail to recognize modules as valid 

![image](https://github.com/user-attachments/assets/164d219e-f8a0-48af-b67d-796ed5bcd5e0)
![image](https://github.com/user-attachments/assets/b1855f5b-1e03-471e-b3a9-3d4ec69413fd)
![image](https://github.com/user-attachments/assets/470e0e56-3df4-4ebf-b2ca-3651a083105b)

**Comment by gabrielpires-1** [comment]
Solved.
